// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXsBY_r00xrykphf_a2VUDteP1WvmsNL0',
    appId: '1:431073767921:web:877db3bd4df7a138cb5450',
    messagingSenderId: '431073767921',
    projectId: 'core-review-c3f7a',
    authDomain: 'core-review-c3f7a.firebaseapp.com',
    storageBucket: 'core-review-c3f7a.appspot.com',
    measurementId: 'G-Y0BXE2SBX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZewopL-OOnHtrl5TOVSK6I1lHCsvGLJA',
    appId: '1:431073767921:android:1851bea99b9ad60ccb5450',
    messagingSenderId: '431073767921',
    projectId: 'core-review-c3f7a',
    storageBucket: 'core-review-c3f7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjZH-9vbRU5bAlAa8rebFf9xbrQmJxgbo',
    appId: '1:431073767921:ios:084850483ff643f2cb5450',
    messagingSenderId: '431073767921',
    projectId: 'core-review-c3f7a',
    storageBucket: 'core-review-c3f7a.appspot.com',
    iosBundleId: 'com.example.devsocCoreReviewProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjZH-9vbRU5bAlAa8rebFf9xbrQmJxgbo',
    appId: '1:431073767921:ios:084850483ff643f2cb5450',
    messagingSenderId: '431073767921',
    projectId: 'core-review-c3f7a',
    storageBucket: 'core-review-c3f7a.appspot.com',
    iosBundleId: 'com.example.devsocCoreReviewProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXsBY_r00xrykphf_a2VUDteP1WvmsNL0',
    appId: '1:431073767921:web:8294603231b1a928cb5450',
    messagingSenderId: '431073767921',
    projectId: 'core-review-c3f7a',
    authDomain: 'core-review-c3f7a.firebaseapp.com',
    storageBucket: 'core-review-c3f7a.appspot.com',
    measurementId: 'G-PWXR1CP64K',
  );
}
